spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/fitnessrecommendations
      database: fitnessrecommendations
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USER_NAME}
    password: ${RABBITMQ_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}

server:
  port : 8083