spring:

  datasource:
    url: jdbc:postgresql://postgres:5432/fitness_db
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/


server:
  port: 8085